export enum GaEnum {
  TR_TRAIN_INFO = "台鐵 info",
  THSR_TRAIN_INFO = "高鐵 info",
  TR_TRAIN_DETAIL_CAPTURE = "台鐵 detail 拍照",
  THSR_TRAIN_DETAIL_CAPTURE = "高鐵 detail 拍照",
  TITLE = "首頁標題",
  TR_TITLE = "台鐵標題",
  THSR_TITLE = "高鐵標題",
  HOME = "首頁 (sidebar)",
  FEATURES = "特色介紹",
  UPDATES = "更新公告",
  CONTACT_ME = "與我聯絡",
  OLD_SYSTEM_ANNOUNCEMENT = "舊系統公告",
  LIGHT_MODE = "亮色模式",
  DARK_MODE = "深色模式",
  CH_LANG = "中文介面",
  EN_LANG = "英語介面",
  TR_ORDER_DESCRIPTION = "台鐵訂票說明",
  HISTORY = "歷史查詢",
}
